server:
  port: 1001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/userdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.haugv.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
